UserManagement/Controllers/ApplicationRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UserManagement.Data;
using Microsoft.AspNetCore.Identity;
using UserManagement.Services;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using UserManagement.Models.IdentityViewModels;

namespace UserManagement.Controllers
{
    public class ApplicationRoleController : Controller
    {
        private readonly RoleManager<ApplicationRole> roleManager;
        private IRoleService roleService;

        public ApplicationRoleController(RoleManager<ApplicationRole> roleManager, IRoleService roleService)
        {
            this.roleManager = roleManager;
            this.roleService = roleService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RoleList([DataSourceRequest] DataSourceRequest request)
        {
            return Json(roleService.Read().ToDataSourceResult(request));
        }

        public async Task<ActionResult> CreateRole([DataSourceRequest] DataSourceRequest request,
        [Bind(Prefix = "models")]IEnumerable<ApplicationRoleVM> roles)
        {
            var results = new List<ApplicationRoleVM>();
            if (roles != null && ModelState.IsValid)
            {
                foreach (var role in roles)
                {
                    await roleService.Create(role);
                    results.Add(role);
                }
            }

            return Json(results.ToDataSourceResult(request, ModelState));
        }

        public async Task<ActionResult> EditRole([DataSourceRequest] DataSourceRequest request,
       [Bind(Prefix = "models")]IEnumerable<ApplicationRoleVM> roles)
        {
            var results = new List<ApplicationRoleVM>();
            if (roles != null && ModelState.IsValid)
            {
                foreach (var role in roles)
                {
                    await roleService.Update(role);
                }
            }

            return Json(results.ToDataSourceResult(request, ModelState));
        }

        public async Task<ActionResult> DeleteRole([DataSourceRequest] DataSourceRequest request,
       [Bind(Prefix = "models")]IEnumerable<ApplicationRoleVM> roles)
        {
            var results = new List<ApplicationRoleVM>();
            if (roles != null && ModelState.IsValid)
            {
                foreach (var role in roles)
                {
                    await roleService.Destroy(role);
                }
            }

            return Json(results.ToDataSourceResult(request, ModelState));
        }
    }
}

UserManagement/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UserManagement.Data;
using Microsoft.AspNetCore.Identity;
using UserManagement.Services;
using Microsoft.AspNetCore.Http;
using Kendo.Mvc.UI;
using UserManagement.Models.IdentityViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Kendo.Mvc.Extensions;

namespace UserManagement.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplicationRole> roleManager;
        private ApplicationDbContext _context;
        private IUserService userService;
        private IHttpContextAccessor httpContext;

        public UserController(IHttpContextAccessor httpContext, UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager, ApplicationDbContext context, IHttpContextAccessor httpContextAccessor, IUserService userService)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            _context = context;
            this.userService = userService;
            this.httpContext = httpContext;
        }

        public IActionResult Index()
        {
            PopulateRoles();
            return View();
        }

        public IActionResult UserList([DataSourceRequest] DataSourceRequest request)
        {
            return Json(userService.Read().ToDataSourceResult(request));
        }

        public IActionResult RoleList([DataSourceRequest] DataSourceRequest request)
        {
            return Json(userService.Read().ToDataSourceResult(request));
        }

        [HttpPost]
        public async Task<ActionResult> CreateUser([DataSourceRequest] DataSourceRequest request,
            [Bind(Prefix = "models")]IEnumerable<UserVM> users)
        {
            var results = new List<UserVM>();
            if (users != null && ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    await userService.Create(user);
                    results.Add(user);
                }
            }

            return Json(results.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> EditUser([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<UserVM> users)
        {
            if (users != null && ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    await userService.Update(user);
                }
            }

            return Json(users.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> DeleteUser([DataSourceRequest] DataSourceRequest request,
          [Bind(Prefix = "models")]IEnumerable<UserVM> users)
        {
            foreach (var user in users)
            {
                await userService.Destroy(user);
            }

            return Json(users.ToDataSourceResult(request, ModelState));
        }

        private void PopulateRoles()
        {

            var roles = roleManager.Roles
                        .Select(c => new RoleVM
                        {
                            RoleId = c.Id,
                            RoleName = c.Name
                        })
                        .OrderBy(e => e.RoleName);

            if (roles.Count() > 0)
            {
                ViewData["roles"] = roles.ToList();
                ViewData["defaultRole"] = roles.First();
            }

        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> UserProfile(string id)
        {
            if (User.Identity.IsAuthenticated == false)
                return RedirectToAction("AccessDenied", "Account");

            ViewData["Reffer"] = Request.Headers["Referer"].ToString();

            var model = new EditUserVM();
            model.ApplicationRoles = roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();

            ApplicationUser user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                model.Name = user.Name;
                model.UserName = user.UserName;
                model.Password = "***";
                model.Email = user.Email;
                model.ApplicationRoleId = roleManager.Roles.Single(r => r.Name == userManager.GetRolesAsync(user).Result.Single()).Name;
            }

            return View(model);
        }

    }
}

UserManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - UserManagement</title>

	<link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    @*<link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.rtl.min.css" />*@

	<link rel="stylesheet" type="text/css" href="~/css/site.css" />
    @RenderSection("styles", required: false)

    <link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.common-fiori.min.css" />
    <link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.mobile.all.min.css" />
    <link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.materialblack.min.css" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/kendo-ui/jszip.min.js"></script>
    <script src="~/lib/kendo-ui/kendo.all.min.js"></script>
    <script src="~/lib/kendo-ui/kendo.aspnetmvc.min.js"></script>
    @*<script src="~/lib/kendo-ui/kendo.messages.fa-IR.min.js"></script>*@
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">UserManagement</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="User" asp-action="Index">Users</a></li>
					<li><a asp-area="" asp-controller="ApplicationRole" asp-action="Index">Roles</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact Me</a></li>
				</ul>
				@await Html.PartialAsync("_LoginPartial")
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 1397 - UserManagement</p>
		</footer>
	</div>


	@RenderSection("Scripts", required: false)
</body>
</html>

UserManagement/Views/Shared/_LoginLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

        <!-- for login page -->
        <link rel="stylesheet" type="text/css" href="~/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" />
        <link rel="stylesheet" type="text/css" href="~/lib/login/vendor/animate/animate.css" />
        <link rel="stylesheet" type="text/css" href="~/lib/login/vendor/css-hamburgers/hamburgers.min.css" />
        <link rel="stylesheet" type="text/css" href="~/lib/login/vendor/select2/select2.min.css" />

        <link rel="stylesheet" type="text/css" href="~/lib/login/css/main.css" />
        <link rel="stylesheet" type="text/css" href="~/lib/login/css/util.css" />

        <style>
            .login-info {
                position: absolute;
                top: 50px;
                left: 50px;
                color: #fff;
            }

            .p-t-190 {
                padding-top: 100px;
            }

            .container-login100::before {
                background: -webkit-linear-gradient(bottom, #ff1f1f, #00c6fb);
            }
        </style>

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>


    <title>_LoginLayout</title>
</head>
<body>
    @RenderBody()


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/login/vendor/bootstrap/js/popper.js"></script>
        <script src="~/lib/login/vendor/select2/select2.min.js"></script>
        <script src="~/lib/login/js/main.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>